#!/bin/bash
# scrape uuid.log for thread uuid statue 
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
awk '/'$1' output start/,/'$1' output end/' "$dir"/../../.appdata/logs/uuid.log | sed 's/.*'"$1"' output start //g' | sed 's/'"$1"' output end//g'
